Pie chart, line graph, and bar chart examples
fusetools/fuse-samples pull request #65
Opened 2017-06-22 10:20 UTC by petterroea

For the premium Charting api

2017-06-22 10:21 UTC, petterroea commented
Samples: https://github.com/fusetools/fuse-samples/pull/65
Documentation: https://github.com/fusetools/premiumlibs/pull/59
Outline and overview documentation: https://github.com/fusetools/fuse-docs/pull/788

2017-06-26 08:19 UTC, kristianhasselknippe requested changes
please also do a spell check on the articles

2017-06-26 08:19 UTC, kristianhasselknippe commented on Samples/BarChart/README.md
> +
it also needs to be added to the .unoproj file

2017-06-26 08:19 UTC, kristianhasselknippe commented on Samples/BarChart/README.md
> +The `Panel` is there for layout-reasons, to make sure the rectangles are in the correct grid, as the `Plot` uses a `GridLayout`. Also worth noting is `PlotArea`, which is used to configure certain as
Please be more clear about what PlotArea is used for here.

2017-06-26 08:19 UTC, kristianhasselknippe commented on Samples/LineGraph/README.md
> +The line-graph renderer should function as a `ux:Class` we can place inside a `Plot` element to have a graph drawn the way we want it. We are therefore interrested in adding a few properties so we ge
interrested -> interested

2017-06-26 08:19 UTC, kristianhasselknippe commented on Samples/LineGraph/README.md
> +The line-graph renderer should function as a `ux:Class` we can place inside a `Plot` element to have a graph drawn the way we want it. We are therefore interrested in adding a few properties so we ge
what is meant by "to have a graph drawn the way we want it."?

2017-06-26 08:19 UTC, kristianhasselknippe commented on Samples/LineGraph/README.md
> +One property of interest, is `SeriesIndex`. If you provide multiple `DataSeries` to a `Plot`, you can use the `SeriesIndex` on a `PlotData` element to select which data series you are drawing from. B
"reading from it locally using" -> "binding to it ..."

2017-06-26 08:19 UTC, kristianhasselknippe commented on Samples/LineGraph/README.md
> +Our line-graph renderer should take a `DataSeries`, and display the data in a nice and consistent way. We can do this using `PlotData`. `PlotData` is like `Each`, but works on every point of data in
`PlotData` is like `Each` -> Is similar to / works like ..

2017-06-26 08:19 UTC, kristianhasselknippe commented on Samples/LineGraph/README.md
> +Notice how the `PlotData` element is inside a `Curve` element. This is because we want to repeat PlotCurvePoints inside a curve, in order to build its shape. As `PlotPoint` doesn't affect a `Curve`,
please specify what you mean by "As `PlotPoint` doesn't affect a `Curve`"

2017-06-26 08:19 UTC, kristianhasselknippe commented on Samples/LineGraph/README.md
> +		<MyPlot Row="0" MainColor="#48B66A" BackgroundColor="#213536" SeriesIndex="2" />
please format this code better and place them in the correct order according to series index (unless that ordering is important).

2017-06-26 08:19 UTC, kristianhasselknippe commented on Samples/LineGraph/README.md
> +Next, some layout stuff. `Plot` doesn't have a default layout, so the most common sense thing to do is to use a `GridLayout`. In this case, we are telling it to reserve 20 pixels at the bottom, which
why is this "common sense"?

2017-06-26 08:19 UTC, kristianhasselknippe commented on Samples/LineGraph/README.md
> +Next, some layout stuff. `Plot` doesn't have a default layout, so the most common sense thing to do is to use a `GridLayout`. In this case, we are telling it to reserve 20 pixels at the bottom, which
"`PlotTicks` produces sane lines" : "sane lines"?

2017-06-26 08:19 UTC, kristianhasselknippe commented on Samples/LineGraph/MainView.ux
> +		<StackPanel Margin="50,50,50,0" Dock="Top" Height="170" Color="#6B76A3" >
is this mockup stuff in the top really necessary?

2017-06-26 08:19 UTC, kristianhasselknippe commented on Samples/PieChart/README.md
> +This example shows how you can create simple, but good looking graphs using the premium Fuse.Charting library. In this example, we will create a reusable line-graph renderer, which will be used to dr
you need to update this text so that it matches the fact that you are making a pie chart:
> create a reusable line-graph renderer
for example

2017-06-26 08:19 UTC, kristianhasselknippe commented on Samples/PieChart/README.md
> +UX expressions are used to color the wedges based on size, and an outer `Panel` is used to size the wedge based on size.
> and an outer `Panel` is used to size the wedge based on size.

what do you mean by this?

2017-06-27 08:04 UTC, petterroea commented on Samples/LineGraph/README.md
> +		<MyPlot Row="0" MainColor="#48B66A" BackgroundColor="#213536" SeriesIndex="2" />
The order is important such that the backmost series is the tallest one.

2017-06-27 08:11 UTC, petterroea commented on Samples/LineGraph/README.md
> +		<MyPlot Row="0" MainColor="#48B66A" BackgroundColor="#213536" SeriesIndex="2" />
Changed the order of data so the ordering can be done properly

2017-06-27 08:11 UTC, petterroea commented on Samples/LineGraph/MainView.ux
> +		<StackPanel Margin="50,50,50,0" Dock="Top" Height="170" Color="#6B76A3" >
I think so, as the chart looks horribily stretched without some filler.

2017-06-27 08:16 UTC, petterroea commented
@kristianhasselknippe changes made

2017-06-27 16:48 UTC, kristianhasselknippe requested changes

2017-06-27 16:48 UTC, kristianhasselknippe commented on Samples/BarChart/README.md
> +    [...]
you don't need the [...] here

2017-06-27 16:48 UTC, kristianhasselknippe commented on Samples/LineGraph/README.md
> +    [...]
same here: remote [...] please

2017-06-27 16:48 UTC, kristianhasselknippe commented on Samples/LineGraph/README.md
> +With that done, you should be all set. Remember to include `Fuse.Charting` package in your unoproj file, like it is done in this example:
also, i would drop the "like it is done in this example" bit

2017-06-27 16:48 UTC, kristianhasselknippe commented on Samples/LineGraph/README.md
> +The line-graph renderer should function as a `ux:Class` we can place inside a `Plot` element, acting as a shortcut to a styled line graph. We are therefore interested in adding a few properties so we
I was more confused by the "should function as a `ux:Class`" here. Try to be less abstract

2017-06-27 16:48 UTC, kristianhasselknippe commented on Samples/LineGraph/README.md
> +One property of interest, is `SeriesIndex`. If you provide multiple `DataSeries` to a `Plot`, you can use the `SeriesIndex` on a `PlotData` element to select which data series you are drawing from. B
"followed by binding to" sounds weird. I suggest something like: "By exposing SeriesIndex` as a property, we can bind to it using a `ReadProperty`-binding. This lets us control what data......."

2017-06-27 16:48 UTC, kristianhasselknippe commented on Samples/LineGraph/README.md
> +Our line-graph renderer should take a `DataSeries`, and display the data in a nice and consistent way. We can do this using `PlotData`. `PlotData` is like `Each`, but works on every point of data in
plz fix

2017-06-27 16:48 UTC, kristianhasselknippe commented on Samples/LineGraph/README.md
> +Notice how the `PlotData` element is inside a `Curve` element. This is because we want to place PlotCurvePoints on a curve, in order to build its shape. Due to `PlotData` being what provides the data
might be worth mentioning that we could have just used two instances of PlotData, although it doesn't make a difference here.

2017-06-27 16:48 UTC, kristianhasselknippe commented on Samples/PieChart/README.md
> +    [...]
same here

2017-06-27 16:48 UTC, kristianhasselknippe commented on Samples/PieChart/README.md
> +UX expressions are used to color the wedges based on size, and an outer `Panel` is used to size the wedges, as the wedges occupy as much space as their parent element.
Please start by explaining the problem that is solved by what you are talking about here. It needs some context to make any sense.

2017-07-03 09:38 UTC, petterroea commented
@kristianhasselknippe cool beans, changes done

2017-07-03 15:08 UTC, kristianhasselknippe requested changes
Please add links to readme.md in root, and we should be good to go :)

2017-07-03 15:08 UTC, kristianhasselknippe commented on Samples/PieChart/README.md
> +UX expressions are used to color the wedges based on size, as sizing the wedges.
> UX expressions are used to color the wedges based on size, as sizing the wedges.
I don't understand this sentence.

2017-07-04 06:44 UTC, petterroea commented
@kristianhasselknippe good to go

2017-07-04 08:02 UTC, kristianhasselknippe commented
@petterroea: there are some conflicts. Would you mind rebasing and squashing your commits?

2017-07-04 08:23 UTC, petterroea commented
Squashed and rebased!

2017-09-13 11:44 UTC, kristianhasselknippe approved these changes

2017-09-13 11:44 UTC, merged